# Generated by Django 2.2.5 on 2019-09-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Top', (('shirt', 'shirt'), ('jacket', 'jacket'), ('hoodie', 'hoodie'), ('jumper', 'jumper'), ('other', 'other'))), ('Trousers', (('jeans', 'jeans'), ('joggers', 'joggers'), ('other', 'other'))), ('shorts', 'shorts'), ('underwear', 'underwear'), ('socks', 'socks'), ('accessory', 'accessory'), ('other', 'other')], max_length=50)),
                ('colour', models.CharField(blank=True, max_length=6)),
                ('joy', models.BooleanField()),
            ],
        ),
    ]
