# Generated by Django 2.2.5 on 2019-09-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='type',
            field=models.CharField(choices=[('Top', (('shirt', 'shirt'), ('jacket', 'jacket'), ('hoodie', 'hoodie'), ('jumper', 'jumper'), ('other', 'other'))), ('Trousers', (('jeans', 'jeans'), ('joggers', 'joggers'), ('other', 'other'))), ('shorts', 'shorts'), ('underwear', 'underwear'), ('socks', 'socks'), ('accessory', 'accessory'), ('other', 'other')], max_length=15),
        ),
    ]
