# Generated by Django 2.2.5 on 2019-09-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20190929_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='colour',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
